### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by carias8** [FARIweb/main_site#10]

**Comment by awacreatives** [comment]
What is "favicon"???

**Comment by awacreatives** [comment]
ok working on it now

**Comment by awacreatives** [comment]
![faviconfari](https://user-images.githubusercontent.com/34777480/36061368-4ce50b08-0e27-11e8-8c42-0d8dda16e9f3.png)

**Comment by awacreatives** [comment]
Please let me know, thank you xoxox

**Comment by awacreatives** [comment]
Please let me know if you need different sizes or formats, thank you

**Comment by carias8** [comment]
We do still need to support mobile favicon but that will be done during the mobile phase of development.
