### ISSUE TITLE
Reformat aboutus

### ISSUE THREAD

**Issue by carias8** [FARIweb/main_site#11]
Currently it has slightly inconsistent use of whitespace. Let's double newline between paragraphs and add better bullets under solinger's section

**Comment by carias8** [comment]
Also the spacing between blue blocks is inconsistent

**Comment by carias8** [comment]
As is the black bar around solinger's box. It'd be nice if it wouldn't stretch with the screen

**Comment by awacreatives** [comment]
[aboutus.zip](https://github.com/FARIweb/main_site/files/1713566/aboutus.zip)

**Comment by awacreatives** [comment]
Hi, Please disregard the previews one:)

**Comment by awacreatives** [comment]
"About Us" page has been corrected and delivered to the repository. Please let me know when you've received it, thank you:)

**Comment by carias8** [comment]
Ah I understand now! This is the ticket you were intending on updating before (instead of #6).

The spacing between the blue blocks is now consistent. Thank you!

We still need to:
- make consistent use of whitespace. double newline between paragraphs. (like in duncan/steven's)
- add better bullets under solinger's section (this seems partly done). Please format it nicer than as is
- inconsistent width on the black bar around solinger's box. It'd be nice if it wouldn't stretch with the screen

**Comment by carias8** [comment]
Changes have been pushed by the way
