### ISSUE TITLE
Same header

### ISSUE THREAD

**Issue by carias8** [FARIweb/main_site#2]
We need to make sure the blog and the main site have the same header.

Specifically they should share the same styles; it should look like the main site and blog are the same site.

**Comment by awacreatives** [comment]
OK:) please give me a call regarding this please

PS: This is issu #2, I can not find issue #1

**Comment by carias8** [comment]
awa called and we discussed exactly what I meant by header. I explained I meant the topmost section with the navigation links. To elaborate on "share the same styles": I meant that it should have a similar look and feel. This might not be totally possible without major rework but just do what you can :)

**Comment by awacreatives** [comment]
[far-test.zip](https://github.com/FARIweb/main_site/files/1876948/far-test.zip)

**Comment by carias8** [comment]
We talked today about how this file just contains the header and nothing else.

We still need to make a new header that matches well with both pages
