### ISSUE TITLE
Picture with BOD: suggest generic picture of a board meeting

### ISSUE THREAD

**Issue by duncanfinlay18** [FARIweb/main_site#21]

**Comment by awacreatives** [comment]
[bod.zip](https://github.com/FARIweb/main_site/files/1691773/bod.zip)
[bod.zip](https://github.com/FARIweb/main_site/files/1691775/bod.zip)

**Comment by awacreatives** [comment]
Good morning, 
Hope all is well. Attached are 6 generic photos we could use. Please let me know if you like any of these. Thank you.

**Comment by awacreatives** [comment]
In the meantime the photo will be replaced with this one:
![serv-img5](https://user-images.githubusercontent.com/34777480/35767513-6381c0b6-08bb-11e8-82fa-8750d0df5cf3.jpg)

**Comment by duncanfinlay18** [comment]
Vey good.  Thanks and hello by the way.  Hope all is well with you.
Duncan


[image: “AliveSciences”] <http://www.alivesci.com/>
G. Duncan Finlay, M.D.| Chief Medical Officer
1803 Glengary St, Sarasota, FL 34231 | M. 941.525.3047
Chief Operating Officer: Darlene Arbeit | Work: 941. <941.525-3047>
914.3999| www.alivesci.com

ATTENTION: This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you are not the named addressee you should not
disseminate, distribute, copy or take any action in reliance on the
contents of this e-mail and these activities are strictly prohibited.
Please notify the sender immediately by e-mail if you have received this
e-mail by mistake and delete this e-mail from your system

**Comment by awacreatives** [comment]
Hello, Hope all is well with you also:)
Thank you.

**Comment by duncanfinlay18** [comment]
Hello to you.  We need to change the Mission Statement as soon as
possible.  New statement: *Improve healthcare delivery by performing and
supporting research to develop and utilize innovative approaches to the
analysis and interpretation of medical data.*
*Thanks*
*Duncan*



[image: “AliveSciences”] <http://www.alivesci.com/>
G. Duncan Finlay, M.D.| Chief Medical Officer
1803 Glengary St, Sarasota, FL 34231 | M. 941.525.3047
Chief Operating Officer: Darlene Arbeit | Work: 941. <941.525-3047>
914.3999| www.alivesci.com

ATTENTION: This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you are not the named addressee you should not
disseminate, distribute, copy or take any action in reliance on the
contents of this e-mail and these activities are strictly prohibited.
Please notify the sender immediately by e-mail if you have received this
e-mail by mistake and delete this e-mail from your system

**Comment by carias8** [comment]
Is this done? Should we pick one of the other pictures?

**Comment by carias8** [comment]
mission was updated at some point
