### ISSUE TITLE
Our Story

### ISSUE THREAD

**Issue by carias8** [FARIweb/main_site#3]
Our story site needs to be updated (or put back into a modal).

Thoughts?

**Comment by awacreatives** [comment]
I have uploaded the new html file to the repository but I can not tell if it overwrote the old one. Can you please let me know. Thank you so much.

**Comment by awacreatives** [comment]
[ourstory.zip](https://github.com/FARIweb/main_site/files/1713285/ourstory.zip)

**Comment by carias8** [comment]
Right now it says I did the latest commit 3 days ago so I don't think anything got uploaded to the actual repo (https://github.com/FARIweb/main_site)

But I noticed the zip file you just uploaded with the one file `ourstory.html`. Before pushing I tested it and it seems to be getting css issues. 

![image](https://user-images.githubusercontent.com/1770481/36064463-5fc82638-0e59-11e8-9b5d-0eb3ba2d9a75.png)

Did you have some new css as well?

Could you also test this on your own machine? Create a new folder and download the repo again but replace this one file then open it up

Thanks though! The parts of it that aren't css-weird look really good!

**Comment by awacreatives** [comment]
Thank you so much. It has been corrected and delivered to the repository.

**Comment by carias8** [comment]
Looks great! Pushed to aws now
