### ISSUE TITLE
Aboutus naming consistency

### ISSUE THREAD

**Issue by carias8** [FARIweb/main_site#6]
On the aboutus page there isn't a consistent display of names/titles. Some have them on new lines, some bold and some have a bullet point by the name.

Anything consistent works but I think title on new line, name+title both bold and no bullet point is the way to go

**Comment by awacreatives** [comment]
[aboutus.zip](https://github.com/FARIweb/main_site/files/1713299/aboutus.zip)

**Comment by awacreatives** [comment]
I have uploaded the new html file to the repository but I can not tell if it overwrote the old one. Can you please let me know. Thank you so much.

**Comment by carias8** [comment]
Sadly no it wasn't uploaded but I went ahead and uploaded it myself. I'm not sure where you're uploading these files besides inside this ticket? The Upload link is on the [main repo page](https://github.com/FARIweb/main_site) next to the Download link

It looks great! Thanks. Go ahead and close this once you read this

**Comment by awacreatives** [comment]
Thank you so much! It has been corrected and delivered to the repository. Please let me know when you've received it, thank you:)

**Comment by carias8** [comment]
Changes were already uploaded. 

Please check your new file for changes and let me know which explicitly they are so that we can track our progress.

**Comment by carias8** [comment]
I understand now that you were actually referring to ticket #11. Please be clear when you're updating and close this ticket once you read this.
