### ISSUE TITLE
Subsections under Our Work

### ISSUE THREAD

**Issue by carias8** [FARIweb/main_site#7]
In index page the subsections under our work (Publications,Symposiums,Associated Publications) does not center align.

Using regular css styles to make it so do not work

**Comment by awacreatives** [comment]
[index.zip](https://github.com/FARIweb/main_site/files/1713569/index.zip)

**Comment by awacreatives** [comment]
Hi, Please check out what I have so far. Give me a call to explain, love you

**Comment by carias8** [comment]
Great. I'll call soon

**Comment by awacreatives** [comment]
I'm working on it now, thank you.

**Comment by carias8** [comment]
Fixed and pushed
